### PR TITLE
Enforce map uri to not start with '/' since this is not supported

### PR DESCRIPTION
**Pull request by tomkerkhove**
When using `/foo` the endpoint is not exposed, but no exception is being thrown as well.

I added a check on this to prevent this from happening for others because it took me a while. Alternative is to remove it instead but I prefer to be explicit and throw an exception.

### CODE REVIEW

**Comment by phnx47** [comment]
Good idea! Thanks!

**Comment by phnx47** [comment]
I already added '/' for MapPath. I think, we don't need use Exception.

**Comment by phnx47** [comment]
In 1.5.0 I will return exception. Start with '/' will be required

**Comment by tomkerkhove** [comment]
That is the problem actually. If I pass /foo the metrics will not be exposed and thus it should throw an exception in my opinion.
________________________________

**Comment by phnx47** [comment]
@tomkerkhove see my code. 
1.4.1 - work with '/' and without '/'
1.5.0 - work with '/' and thow Exception without '/'

**Comment by tomkerkhove** [comment]
I'm on 1.4 and will upgrade but don't really see where you throw the exception except for my addition?

**Comment by phnx47** [comment]
https://github.com/phnx47/Prometheus.Client.Owin/blob/e9c165192ea09156952dc843df0d00b67bcf8a05/src/Prometheus.Client.Owin/PrometheusExtensions.cs#L38

I will release it after: https://github.com/phnx47/Prometheus.Client.Owin/issues/4

**Pull request merged**
